### ISSUE TITLE
Create Polygon Class framework

### ISSUE THREAD

**Issue by debeshmandal** [shanilpanara/origamiUROP#2]
## Summary
Create a class or set of classes that can be used to generate 2D/3D polygons and exported in standardised file format.

### Example of Vertex and Edge classes:
```python
class Vertex():
    '''
    A Vertex is a point in space that is connected to other vertices
    '''
    def __init__(self, position : np.ndarray):
        self.position = position

    def distance(self, vertex : Vertex) -> float:
        return np.linalg.norm(self.position - vertex.position)

class Edge(): 
    ''' 
    An Edge connects two vertices and stores geometric information about this connection 
    '''
    def __init__(self, vertex_1 : Vertex, vertex_2 : Vertex):  
        self.vertices = (vertex_1, vertex_2) 

    def __len__(self):
        return self.vertices[0].distance(self.vertices[1])

    @property 
    def vector(self) -> np.ndarray: 
        return self.vertices[1] - self.vertices[0]

```
### Vertex Class
- should store position

### Edge Class
- Collection of 2 vertices
- have length, vector properties

### Polygon Class
- Collection of edges
- Container for writing files

## Tasks
- [ ] create `Vertex` class
- [x] create `Edge` class
- [x] create `Polygon` (can have different name) class to store this information
- [x] add `Polygon.write_PLY(fout)` or `Polygon.write_STL(fout)`

**Comment by shanilpanara** [comment]
Should I have both classes in the same Python file? That's not wrong, right?

**Comment by debeshmandal** [comment]
do it however you want - if it turns out later that it's a bit messy, we can rearrange the structure in a different branch

**Comment by shanilpanara** [comment]
## Polygon
### Inputs structure:
- Array of x, y (& z) coordinates of verticies. Needs atleast 3 verticies, written cyclicly - in the way they should join.
```python
verticies = [
    [x, y]
    [0, 0]
    [1, 2]
    [2, 4]
    [5, 0]
]
```
- Also compatibility for other polygon objects (which do not intersect, but are larger or smaller - i.e. a shape inside a shape)
### Attributes:
- [ ] No. of verticies
- [ ] No. of Edges
- [ ] Length of each edge
- [ ] Vectors defining each edge
- [ ] Define --> Find boundary using edge vectors
### Methods 
- [ ] Check it is a closed polygonal shape & not self-intersecting
- [ ] If there are multiple polygons, ensure they dont intersect each other
- [ ] Draw polygon(s) -> 
- - [ ] label each edge with a corresponding number or vector or length
- - [ ] label each vertex with a corresponding number and coordinates
- [ ] List all the points on a boundary
- [ ] Distance between any two points on a boundary
- [ ] Writing to file as:
- - [ ] .stl (ASCII)
- - [ ] .ply

## My thoughts
@debeshmandal maybe I'm missing something, but doesn't it make more sense to use one class (Polygon) and define vertex and edge as attributes/properties, such that one could initialise a polygon using something along the lines:
```python
verticies = [
    [0, 0]
    [0, 1]
    [1, 1]
    [1, 0]
]
square = Polygon(verticies)
```
and then the class would automatically calculate everything just these values.

**Comment by debeshmandal** [comment]
I think we will need the `Edge` class for sure since it will be the basis for creating DNA strands. The `Vertex` class maybe we don't need to feel free to omit that. (PS it's spelled vertices not verticies)

Maybe what you can do is initialise the polygon as you have described (i.e. `square = Polygon(vertices)`) and have a function/property that generates a list of `Edges`

**Comment by debeshmandal** [comment]
Some of the things you have described as attributes will have to become `@property` methods instead but I think overall you're on the right track

**Comment by debeshmandal** [comment]
we're <b>not</b> subclassing here. Subclassing would be something like:

```python
class Square(Polygon):
    def __init__(self, length):
        vertices = length * np.array([
            [0.0, 0.0],
            [0.0, 1.0],
            [1.0, 1.0],
            [1.0, 0.0]
        ])
        super().__init__(vertices)
```

**Comment by debeshmandal** [comment]
either you have to create the set of `Edge` instances first and then pass them as arguments to `Polygon.__init__` or you have to create the set of `Edge` instances using a method/property of `Polygon` -> I'm not sure which is better in the long run, but try and write the code so that if we want to change then it is not too awkward.

**Comment by debeshmandal** [comment]
Also please use length 3 arrays so that there is the option for other users and also in the future if we choose to use 3D to do so. It won't affect anything massively at this stage - once we start populating with DNA, we'll still use 3D arrays but do 2D design - I discussed this with Stefano yesterday

**Comment by shanilpanara** [comment]
Thanks for all the replies (and so speedy too!) - I think I understand everything you've said & it's probably best for me to just get started now as I'll my understanding of the structure will improve as I start to implement it. I'll add any other attributes, '@property methods' and methods if I think of any

If I get really stuck I'll give you a shout & to begin with I'll focus on getting the input and output (.stl / .ply) :)

**Comment by shanilpanara** [comment]
## Current Structure
### Edges
#### Attributes
- [x] Vertices
- [x] Edge Type (boundary, scaffold, staple)
_This is so we can determine which edge objects to convert to DNA, will hopefully be useful later_ 
- [ ] Linear Velocity
- [ ] Angular Velocity
#### Methods
- [x] Length of edge (float)
#### Property Method
- [x] Vector
- [x] Unit Vector (i.e direction)
### BoundaryPolygon
#### Attributes
- [x] Verticies
- [x] x , y , z
- [x] Number of edges
- [x] Edges (each instance stored within the BoundaryPolygon class)
#### Methods
- [x] Writing to file: STL
- [ ] Writing to file: PLY
- [ ] Find area/volume where the scaffold can be placed
- - [ ] For a given resolution: find all points on the boundary
- - [ ] Ensure polygon it is not self intersecting
- - [ ] Find the "active area" enclosed in the shape
- - [ ] Plot it (to see if it's worked)
### Other methods
- [x] Creating "Edge" instances when BoundaryPolygon is made
- [x] Plotting vertices of BoundaryPolygon

@debeshmandal I've fleshed out where the program is currently at and some my thoughts on what can be added next. Let me know if you think I might be running offcourse a little :)

**Comment by debeshmandal** [comment]
@shanilpanara everything looks good, i'm impressed - there is some tidying up and some tests to create - I will make a branch of your branch, and make a new pull request with some changes that I will make to tidy things up, split up the code and make the continuous integration work. Don't do any more coding on this branch, especially related to DNA - we will use a separate issue and pull request for  that.

**Comment by debeshmandal** [comment]
Also, I think that the triangulation is good, and may actually be very useful; however it's not exactly what we need at the moment, since it creates triangles inside the shape that are not Edge instances (I think) so that may need some tweaking but I like the idea of the triangulation because it adds more complexity to the design - see if you can read up on different triangulation algorithms because we can try to implement them to allow the scaffold to take different paths for the same boundary shape.

**Comment by shanilpanara** [comment]
Okay amazing, I tidied a few small things up this morning, but nothing major, I'll push the newest version in just a mo and then leave it :)

> @shanilpanara everything looks good, i'm impressed - there is some tidying up and some tests to create - I will make a branch of your branch, and make a new pull request with some changes that I will make to tidy things up, split up the code and make the continuous integration work. Don't do any more coding on this branch, especially related to DNA - we will use a separate issue and pull request for that.

**Comment by shanilpanara** [comment]
I did quite a bit of researching and thinking how to make stl files. And the triangulation seemed to be the simplest way that I could wrap my head around.

One thing I don't quite understand yet is why we're making .stl/.ply files? Is it the input files for oxDNA? Or just to visualize the structures we're making along the way? 

Also you're right in saying the the Edge instances do not include those triangles, the triangulation is purely for how we view it (through the .stl file)

When you say different paths for the same boundary shape, do you mean rather than "filling" the shape, instead creating "lines" of a specific thickness, i.e. creating a "line drawing" using just the vertices.

> Also, I think that the triangulation is good, and may actually be very useful; however it's not exactly what we need at the moment, since it creates triangles inside the shape that are not Edge instances (I think) so that may need some tweaking but I like the idea of the triangulation because it adds more complexity to the design - see if you can read up on different triangulation algorithms because we can try to implement them to allow the scaffold to take different paths for the same boundary shape.

**Comment by debeshmandal** [comment]
@shanilpanara I've made a mistake regarding STL files - we actually want PLY files. The reason for this is because it is important to use existing/standardised/open-source file formats when possible. In reality our main use for this will be visualisation - but also further down the line, we/someone else may want to design a polygon/polyhedra not using Python - and so reading STL/PLY files will allow the use of external programs improving the usability and accessibility of our program. One of the next stages will be reading a PLY file (I think we'll probably ignore STL for now) and create a `Polygon` instance which can be populated with DNA.

What you've done so far is good - apologies that STL was not the right way to go; I will add a method called write_PLY so create the PLY file and then we can wrap up this issue and pull request.

**Comment by shanilpanara** [comment]
> @shanilpanara I've made a mistake regarding STL files - we actually want PLY files. The reason for this is because it is important to use existing/standardised/open-source file formats when possible. In reality our main use for this will be visualisation - but also further down the line, we/someone else may want to design a polygon/polyhedra not using Python - and so reading STL/PLY files will allow the use of external programs improving the usability and accessibility of our program. One of the next stages will be reading a PLY file (I think we'll probably ignore STL for now) and create a `Polygon` instance which can be populated with DNA.
> 
> What you've done so far is good - apologies that STL was not the right way to go; I will add a method called write_PLY so create the PLY file and then we can wrap up this issue and pull request.

Okay fab, no worries! I'll get looking into writing PLY files.

**Comment by debeshmandal** [comment]
It's cool, I'll do the PLY code as part of this update - have a look at the [oxDNA model](https://aip.scitation.org/doi/10.1063/1.4921957) and we can discuss - after discussing testing (which I will try to set up as well). 

Please just commit and push all code that you have worked on.

Our next end point is successfully simulating the Polygon populated with DNA using LAMMPS (still a while away from that at the moment), and we will do this by using existing oxDNA tools to create an oxDNA system, which we will write to a LAMMPS file - there's a lot of new things to read up on, so I think it's probably best that you try to familiarise yourself a little with the following:

- tacoxDNA (in the other issue)
- the code for generating single/double helices (might be difficult to understand but worth a shot) (in the other issue)
- [Molecular dynamics](https://www.youtube.com/watch?v=veBZYlD6AF4) potentials
- [oxDNA2](https://aip.scitation.org/doi/10.1063/1.4921957)
- [LAMMPS](https://www.youtube.com/watch?v=QdygibMW1AI) (quite long!)

**Comment by shanilpanara** [comment]
Got it! Also, I looked again and I didn't make any major changes since the last push, so the version you have is the most update to date version!

Will begin reading/trying to grasp all of the above 👍🏽

**Comment by shanilpanara** [comment]
Got it! Also, I looked again and I didn't make any major changes since the last push, so the version you have is the most update to date version!

Will begin reading/trying to grasp all of the above 👍🏽

**Comment by debeshmandal** [comment]
@shanilpanara I'm closing this now - remember that it exists (can be found in issues -> closed) because of the notes above
