### ISSUE TITLE
initialise .travis.yml and pytest

### ISSUE THREAD

**Issue by debeshmandal** [shanilpanara/origamiUROP#3]
## Summary
Ensure Continuous Integration runs successfully and that pytest folder structure has been created and works

## Tasks
- [x] link Travis CI to Github (for Shanil)
- [x] create pytest folders and placeholder files (for Debesh)
- [x] create .travis.yml file
